# config.yaml

defaults:
  - _self_
  - model: unet_hrnet_w64
  - augmentations: Resize1024_R

mode: 'train'  # Default mode

model_path: null  # Initially set to null; can be specified via command line

IMAGE_ROOT: './data/train/DCM'
LABEL_ROOT: './data/train/outputs_json'
TEST_IMAGE_ROOT: './data/test/DCM'

BATCH_SIZE: 2
LR: 1e-4
RANDOM_SEED: 2024

NUM_EPOCHS_PHASE1: 100  # Number of epochs for Phase 1
PHASE2_RATIO: 0.2       # Ratio of epochs for Phase 2 (20% of Phase 1)

VAL_EVERY: 10
SAVED_DIR: 'checkpoints'
LOG_TOOL: 'wandb'  # Or 'tensorboard'

# Data splitting mode
data_split_mode: 'two_phase'  # 'kfold' or 'two_phase'

# Early Stopping configuration
early_stopping:
  enabled: true        # Enable Early Stopping
  patience: 5          # Number of epochs to wait for improvement
  mode: 'max'          # 'max' or 'min' (e.g., val_dice is 'max', val_loss is 'min')
  min_delta: 0.001     # Minimum change to qualify as an improvement

# Loss function mode
loss_mode: 'multiclass'  # 'binary', 'multiclass', 'multilabel'

# Predefine new keys
CLASS2IND: {}
IND2CLASS: {}

CLASSES:
  - 'finger-1'
  - 'finger-2'
  - 'finger-3'
  - 'finger-4'
  - 'finger-5'
  - 'finger-6'
  - 'finger-7'
  - 'finger-8'
  - 'finger-9'
  - 'finger-10'
  - 'finger-11'
  - 'finger-12'
  - 'finger-13'
  - 'finger-14'
  - 'finger-15'
  - 'finger-16'
  - 'finger-17'
  - 'finger-18'
  - 'finger-19'
  - 'Trapezium'
  - 'Trapezoid'
  - 'Capitate'
  - 'Hamate'
  - 'Scaphoid'
  - 'Lunate'
  - 'Triquetrum'
  - 'Pisiform'
  - 'Radius'
  - 'Ulna'

PALETTE:
  - [220, 20, 60]
  - [119, 11, 32]
  - [0, 0, 142]
  - [0, 0, 230]
  - [106, 0, 228]
  - [0, 60, 100]
  - [0, 80, 100]
  - [0, 0, 70]
  - [0, 0, 192]
  - [250, 170, 30]
  - [100, 170, 30]
  - [220, 220, 0]
  - [175, 116, 175]
  - [250, 0, 30]
  - [165, 42, 42]
  - [255, 77, 255]
  - [0, 226, 252]
  - [182, 182, 255]
  - [0, 82, 0]
  - [120, 166, 157]
  - [110, 76, 0]
  - [174, 57, 255]
  - [199, 100, 0]
  - [72, 0, 118]
  - [255, 179, 240]
  - [0, 125, 92]
  - [209, 0, 151]
  - [188, 208, 182]
  - [0, 220, 176]

threshold: 0.5
output_size: [2048, 2048]

# TTA 설정 추가
inference:
  use_tta: true  # 추론 시 TTA를 사용할지 여부 (true/false)
  transforms:
    - HorizontalFlip
    - VerticalFlip
    - Rotate90
    # 필요에 따라 추가 변환을 여기에 나열할 수 있습니다.

# Hydra configuration
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    root:
      handlers: null  # Configure logging

# Optimizer configuration
optimizer:
  name: 'lion'  # Supported optimizers: 'adam', 'sgd', 'rmsprop', 'lion'
  params: {}      # Optionally override default parameters

optimizer_defaults:
  adam:
    lr: 1e-4
    weight_decay: 1e-5
    betas: [0.9, 0.999]
  adamw:
    lr: 1e-4
    weight_decay: 1e-2
    betas: [0.9, 0.999]
    eps: 1e-08
    amsgrad: false
  sgd:
    lr: 1e-2
    weight_decay: 1e-4
    momentum: 0.9
    nesterov: false
  rmsprop:
    lr: 1e-4
    weight_decay: 1e-5
    momentum: 0.9
    alpha: 0.99
  lion:              # Lion optimizer default settings
    lr: 1e-4
    weight_decay: 0.0
    betas: [0.9, 0.99]

# Scheduler configuration
scheduler:
  name: 'cosine_annealing'  # Supported schedulers: 'step_lr', 'reduce_on_plateau', 'cosine_annealing', etc.
  params: {}         # Optionally override default parameters

scheduler_defaults:
  step_lr:
    step_size: 10
    gamma: 0.1
  reduce_on_plateau:
    mode: 'max'
    factor: 0.1
    patience: 5
    threshold: 0.0001
    threshold_mode: 'rel'
    cooldown: 0
    min_lr: 0
    eps: 1e-08
  cosine_annealing:
    T_max: 50
    eta_min: 0

# Loss 설정 추가
loss:
  name: 'dice'  # 사용 가능한 손실 함수: 'bce', 'dice', 'jaccard', 'focal', 'tversky'

inference_to_gpu: True
