model:
  library: "smp"
  architecture:
    base_model: "PSPNet"
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    encoder_depth: 3  #[3, 5], default is 5
    psp_out_channels: 512
    psp_use_batchnorm: True # True, False, inplace
    psp_dropout: 0.2 # [0, 1)
    in_channels: 3
    classes: 29
    activation: null # “sigmoid”, “softmax”, “logsoftmax”, “tanh”, “identity”
    upsampling: 8 # Final upsampling factor. Default is 8 to preserve input-output spatial shape identity
    