model:
  module: 'segmentation_models_pytorch'
  library: 'smp'
  base_model: 'PAN'
  checkpoint: null
  architecture:
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    encoder_output_stride: 16 # 16 or 32, if 16 use dilation in encoder last layer, Doesn’t work with *ception*, vgg*, densenet*`
    decoder_channels: 32 # A number of convolution layer filters in decoder blocks
    in_channels: 3
    classes: 29
    activation: null # “sigmoid”, “softmax”, “logsoftmax”, “tanh”, “identity”
    upsampling: 4 # Final upsampling factor. Default is 4 to preserve input-output spatial shape identity