train:
  - type: Resize
    params:
      height: 512
      width: 512
  - type: ElasticTransform
    params:
      alpha: 1.0
      sigma: 50.0
      alpha_affine: 50.0
      p: 0.5
val:
  - type: Resize
    params:
      height: 512
      width: 512
