# config/augmentations/Resize1024.yaml

train:
  - type: Resize
    params:
      height: 1024
      width: 1024
      p: 1.0
  - type: Rotate
    params:
      limit: 30
      p: 0.5
val:
  - type: Resize
    params:
      height: 1024
      width: 1024

