data :
  train_data_path : '/data/ephemeral/home/data/train/DCM'
  train_label_path : '/data/ephemeral/home/data/train/outputs_json'
  test_data_path : '/data/ephemeral/home/data/test/DCM'
  classes : [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
  ]

  fold : 0
  split_method : GroupKFold


  train : 
    batch_size : 4
    shuffle : True
    num_workers : 2
    pin_memory : True
    drop_last : True
    print_step: 20
    ratio : 0.8
    early_stopping_patience : 5
    early_stopping_delta : 0.001
    max_epoch : 100
    

  valid : 
    batch_size : 4
    shuffle : False
    num_workers : 2
    pin_memory : True
    drop_last : False
    interval: 5
    threshold: 0.5

    interpolate:
      nearest: 'nearest'
      bilinear: 'bilinear'
      bicubic: 'bicubic'
      area: 'area'
      lanczos: 'lanczos'

  

  test : 
    batch_size : 4
    shuffle : False
    num_workers : 2
    pin_memory : True
    drop_last : False
  

augmentation:
  train:
    - Resize:
        height: 512
        width: 512
    - Rotate:
        limit: 10
        p: 0.5
    - CLAHE:
        clip_limit: 4.0
        tile_grid_size: [8, 8]  
        p: 0.5
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    

  valid:
    - Resize:
        height: 512
        width: 512
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  test :
    - Resize:
        height: 1024
        width: 1024
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

save:
  # 실험 config 저장 경로
  save_config: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/configs
  # 체크포인트 저장 경로
  save_ckpt: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/checkpoints

seed: 42
loss_func: 
  name: BCEWithLogitsLoss
optimizer: 
  name: Adam
  lr: 1e-4
  weight_decay: 1e-6

# 추후에 설정
# scheduler:
  # name: CosineAnnealingLR
  # T_max: 50
  # eta_min: 0  # default
  # last_epoch: -1  # default

# 디버깅 모드
debug: False
inference:
  threshold: 0.5
  output_size: [2048, 2048]  # 튜플을 리스트로 수정
  checkpoint_path: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/checkpoints/lraspp_mobilenet/lraspp_mobilenet_v3_large_best_model.pt"  # .ckpt에서 .pt로 수정
  output_dir: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/results"