data :
  train_data_path : '/data/ephemeral/home/data/train/DCM'
  train_label_path : '/data/ephemeral/home/data/train/outputs_json'
  test_data_path : '/data/ephemeral/home/data/test/DCM'
  classes : [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
  ]

  fold : 0

  split_method : GroupKFold

  train : 
    batch_size : 4
    shuffle : True
    num_workers : 2
    pin_memory : True
  
  valid : 
    batch_size : 4
    shuffle : True
    num_workers : 2
    pin_memory : True
  
  test : 
    batch_size : 4
    shuffle : True
    num_workers : 2
    pin_memory : True
  

augmentation:
  train:
    - Resize:
        height: 512
        width: 512
    - Rotate:
        limit: 10
        p: 0.5
    - CLAHE:
        clip_limit: 4.0
        tile_grid_size: [8, 8]  
        p: 0.5
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    

  valid:
    - Resize:
        height: 512
        width: 512
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  test :
    - Resize:
        height: 512
        width: 512


train:
  classes: 29
  batch_size: 8
  max_epoch: 20
  print_step: 25
val:
  batch_size: 4
  interval: 5
  threshold: 0.5

save_dir: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/checkpoints/basemodel

seed: 42

loss_name: BCEWithLogitsLoss

optimizer: 
  name: Adam
  lr: 1e-4
  weight_decay: 1e-6

# 디버깅 모드
debug: True



library: 'torchvision'
model_name: 'fcn_resnet50'
num_classes: 29
pretrained: True
