data :
  train_data_path : '/Users/jeongseungmin/Desktop/Study/datacentric/Data/train/DCM'
  train_label_path : '/Users/jeongseungmin/Desktop/Study/datacentric/Data/train/outputs_json'
  test_data_path : '/Users/jeongseungmin/Desktop/Study/datacentric/Data/test/DCM'
  class : [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
  ]

augmentation:
  train:
    - Resize:
        height: 512
        width: 512
    - Rotate:
        limit: 10
        p: 0.5
    - CLAHE:
        clip_limit: 4.0
        tile_grid_size: [8, 8]  
        p: 0.5
    - BrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.3
        p: 0.5
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    
    

  valid:
    - Resize:
        height: 512
        width: 512
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]