data:
  train_data_path: /data/ephemeral/home/data/train/DCM
  train_label_path: /data/ephemeral/home/data/train/outputs_json
  test_data_path: /data/ephemeral/home/data/test/DCM
  classes:
  - finger-1
  - finger-2
  - finger-3
  - finger-4
  - finger-5
  - finger-6
  - finger-7
  - finger-8
  - finger-9
  - finger-10
  - finger-11
  - finger-12
  - finger-13
  - finger-14
  - finger-15
  - finger-16
  - finger-17
  - finger-18
  - finger-19
  - Trapezium
  - Trapezoid
  - Capitate
  - Hamate
  - Scaphoid
  - Lunate
  - Triquetrum
  - Pisiform
  - Radius
  - Ulna
  fold: 0
  split_method: GroupKFold
  train:
    batch_size: 4
    shuffle: true
    num_workers: 2
    pin_memory: true
    drop_last: true
  valid:
    batch_size: 4
    shuffle: false
    num_workers: 2
    pin_memory: true
    drop_last: false
  test:
    batch_size: 4
    shuffle: false
    num_workers: 2
    pin_memory: true
    drop_last: false
augmentation:
  train:
  - Resize:
      height: 512
      width: 512
  - Rotate:
      limit: 10
      p: 0.5
  - CLAHE:
      clip_limit: 4.0
      tile_grid_size:
      - 8
      - 8
      p: 0.5
  - Normalize:
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  valid:
  - Resize:
      height: 512
      width: 512
  - Normalize:
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  test:
  - Resize:
      height: 1024
      width: 1024
  - Normalize:
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
train:
  classes: 29
  batch_size: 4
  max_epoch: 3
  print_step: 1
  ratio: 0.8
  early_stopping_patience: 5
  early_stopping_delta: 0.001
val:
  batch_size: 4
  interval: 1
  threshold: 0.5
save_dir: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/checkpoints/basemodel
seed: 42
loss_name: BCEWithLogitsLoss
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 1.0e-06
debug: false
inference:
  threshold: 0.5
  output_size:
  - 2048
  - 2048
  checkpoint_path: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/checkpoints/lraspp_mobilenet/lraspp_mobilenet_v3_large_best_model.pt
  output_dir: /data/ephemeral/home/level2-cv-semanticsegmentation-cv-22-lv3/results
model:
  library: smp
  architecture:
    base_model: FPN
    encoder_name: resnet50
    encoder_depth: 5
    encoder_weights: imagenet
    decoder_pyramid_channels: 256
    decoder_segmentation_channels: 128
    decoder_merge_policy: add
    decoder_dropout: 0.2
    in_channels: 3
    classes: 29
    activation: null
    upsampling: 4
