model:
  module: 'torchvision.models.segmentation'
  library: 'torchvision'
  base_model: 'deeplabv3_resnet101'
  checkpoint: None
  architecture:
    weights: 'DeepLabV3_ResNet101_Weights.DEFAULT'
    progress: True
    aux_loss: False