model:
  module: 'torchvision.models.segmentation'
  library: 'torchvision'
  checkpoint: null
  base_model: 'fcn_resnet101'
  architecture:
    weights: 'FCN_ResNet101_Weights.DEFAULT'
    progress: True
    aux_loss: False