# batch_size
train:
  classes: 29
  batch_size: 8
  max_epoch: 20
val:
  batch_size: 4
  interval: 5

save_dir: ./checkpoints/basemodel

seed: 42

loss_name: BCEWithLogitsLoss

optimizer: 
  name: Adam
  lr: 1e-4
  weight_decay: 1e-6

# 디버깅 모드
debug: False